routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//initialized Controler

Route::resource('bookStore', 'Book');
Route::resource('category', 'BookCategory');

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard', function () {
    return view('dashboard.main');
});

Route::get('/ManageBook', function() {
    $data['data_book'] = \App\M_BookStore::join('category_books','category_books.category_id' , '=' , 'book_stores.category_id')->get();
    return view('dashboard.manageBook', $data);
});


Auth::routes();

Route::get('/loginHome', 'LoginHome@index')->name('loginHome');

app/M_Admin.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class M_Admin extends Authenticatable
{
    use Notifiable;

    protected $table = "admin";
    protected $primaryKey = 'admin_id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone_number'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/M_BookStore.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class M_BookStore extends Model
{
    protected $table = "book_stores";
    protected $primaryKey = "book_id";
}

app/M_CategoryBook.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class M_CategoryBook extends Model
{
    protected $table = "category_books";
    protected $primaryKey = "category_id";
}

app/Http/Controllers/Book.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class Book extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['data_book'] = \App\M_BookStore::join('category_books','category_books.category_id' , '=' , 'book_stores.category_id')->get();
        return view('dashboard.listBook', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['data_category'] = \App\M_CategoryBook::all();
        return view('dashboard.addbook' , $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'book_name' => 'required|string|unique:book_stores'
        ]);

        $data = new \App\M_BookStore();
        $data->category_id = $request->b_catalog;
        $data->book_name = $request->book_name;
        $data->description = $request->b_deskrip;
        $data->price = $request->b_price;
        $data->total_stuff = $request->b_total_stuff;
        $data->save();
        return redirect()->route('bookStore.index')->with('alert-success','Success Add book');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['data_book'] = \App\M_BookStore::join('category_books','category_books.category_id' , '=' , 'book_stores.category_id')
        ->where('book_id' , $id)->get();
        $data['data_catalog'] = \App\M_CategoryBook::all();
        return view('dashboard.editBook', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = $request->validate([
            'book_name' => 'required|string|unique:book_stores'
        ]);
        
        $data = \App\M_BookStore::where('book_id' , $id)->first();
        $data->category_id = $request->b_catalog;
        $data->book_name = $request->b_name;
        $data->description = $request->b_deskrip;
        $data->price = $request->b_price;
        $data->total_stuff = $request->b_total_stuff;
        $data->save();
        return redirect()->route('bookStore.edit' , $id)->with('alert-success','Data has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = \App\M_BookStore::findOrFail($id);
        $data->delete();
        return redirect('/ManageBook');
    }
}

app/Http/Controllers/BookCategory.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class BookCategory extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['data_category'] = \App\M_CategoryBook::all();
        return view('dashboard.category', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.addCategory');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'category_name' => 'required|string|unique:category_books'
        ]);
    }


    public function store(Request $request)
    {
        $validator = $request->validate([
            'category_name' => 'required|string|unique:category_books'
        ]);

        $data = new \App\M_CategoryBook();
        $data->category_name = $request->category_name;
        $data->description = $request->c_deskrip;
        $data->save();
        return redirect()->route('category.index')->with('alert-success','Success Add Category');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = \App\M_CategoryBook::findOrFail($id);
        $data->delete();
        return redirect()->route('category.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LoginHome.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LoginHome extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('loginHome');
    }
}

resources/views/dashboard/addCategory.blade.php
@extends('mainTheme.main') 

@section('title' , 'Add New Category')

@section('content')

<div class="container-fluid">
  <div class="row">
      <div class="col-lg-12">
        <div class="g-card">
        <div class="in-card">
        <form action="{{ route('category.store') }}" class="form" method="post">
          {{ csrf_field() }}

          <h5>New Category Here</h5>
          <p class="text-right smallin">Silahkan isi sesuai dengan ketentuan</p>
          <div class="my-3"></div>
          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Category Name<br>
                <span class="small40li">Sesuaikan nama center anda dengan benar</span><br>
                
              </p>
            </div>
            <div class="col-lg-7">
              <div class="form-group">
                <label for="first" class="form-label">ex: Social</label>
                <input id="first" class="form-input" type="text" name="category_name" class="form-control{{ $errors->has('category_name') ? ' is-invalid' : '' }}" />
                @if ($errors->has('category_name'))
                      <span class="small40li" style="color:red">
                          <strong>{{ $errors->first('category_name') }}</strong>
                      </span>
                @endif
              </div>
            </div>
          </div>
          
          <hr class="my-5">
          
          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Category Deskription <br>
                <span class="small40li">Sesuaikan nama center anda dengan benar</span>
              </p>
            </div>

            <div class="col-lg-7">
              <div class="form-group">
                  <label for="second" class="form-label">ex: Social learn about....</label>
                  <textarea id="second" class="form-input" name="c_deskrip" rows="6"></textarea>
              </div>
            </div>
          </div>



          <div class="my-5"></div>

          <div class="row">
            <div class="col-lg-12">
              <button type="submit" class="btn btn-primary">Save The Category</button>
            </div>
          </div>
          
          <div class="my-5"></div>

        </form>

        </div>
      </div>
      </div>

  </div>
</div>

@endsection

resources/views/dashboard/addbook.blade.php
@extends('mainTheme.main') 

@section('title' , 'Add New Book')

@section('content')

<div class="container-fluid">
  <div class="row">
      <div class="col-lg-12">
        <div class="g-card">
        <div class="in-card">
        <form action="{{ route('bookStore.store') }}" class="form" method="post">
          {{ csrf_field() }}

          <h5>New Book Here</h5>
          <p class="text-right smallin">Silahkan isi sesuai dengan ketentuan</p>
          <div class="my-3"></div>
          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Book Name<br>
                <span class="small40li">Sesuaikan nama center anda dengan benar</span>
              </p>
            </div>
            <div class="col-lg-7">
              <div class="form-group">
                <label for="first" class="form-label">ex: Learning Laravel</label>
                <input id="first" class="form-input" type="text" name="book_name" class="form-control{{ $errors->has('book_name') ? ' is-invalid' : '' }}" />
                @if ($errors->has('book_name'))
                      <span class="small40li" style="color:red">
                          <strong>{{ $errors->first('book_name') }}</strong>
                      </span>
                @endif
              </div>
            </div>
          </div>
          
          <hr class="my-5">
          
          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Book Deskription <br>
                <span class="small40li">Sesuaikan nama center anda dengan benar</span>
              </p>
            </div>

            <div class="col-lg-7">
              <div class="form-group">
                  <label for="second" class="form-label">ex: this book make....</label>
                  <textarea id="second" class="form-input" name="b_deskrip" rows="6"></textarea>
              </div>
            </div>
          </div>

          <hr class="my-5">

          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Price <br>
                <span class="small40li">Sesuaikan nama center anda dengan benar</span>
              </p>
            </div>

            <div class="col-lg-7">
              <div class="form-group">
                <label for="first" class="form-label">ex: Rp. 30,000</label>
                <input id="first" class="form-input" type="number" name="b_price"/>
              </div>
            </div>
          </div>

          <hr class="my-5">

          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Total Stuff <br>
                <span class="small40li">Sesuaikan nama center anda dengan benar</span>
              </p>
            </div>

            <div class="col-lg-7">
              <div class="form-group">
                <label for="first" class="form-label">ex: 200 Pcs</label>
                <input id="first" class="form-input" type="number" name="b_total_stuff"/>
              </div>
            </div>
          </div>

          <hr class="my-5">

          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Catalog
                <br>
                <span class="small40li">NB: Before using it. Make Category in "Book Category"</span>
              </p>
            </div>

            <div class="col-lg-7">
              <div class="form-group">
                <select class="form-control form-input" name="b_catalog">
                    @foreach ($data_category as $item)
                        <option value="{{ $item->category_id }}">{{ $item->category_name }}</option>
                    @endforeach
                </select>
              </div>
            </div>
          </div>

          <div class="my-5"></div>

          <div class="row">
            <div class="col-lg-12">
              <button type="submit" class="btn btn-primary">Save The Product</button>
            </div>
          </div>
          
          <div class="my-5"></div>

        </form>

        </div>
      </div>
      </div>

  </div>
</div>

@endsection

resources/views/dashboard/category.blade.php
@extends('mainTheme.main') 

@section('title' , 'Category')

@section('content') @if(Session::has('alert-success'))
<div class="alert alert-success">
    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
</div>
@endif
<div class="container-fluid">
    <div class="row">
        {{-- the batas konten --}}
        <div class="col-lg-12 g-card">
            <div class="in-card">
            <h5>List Product</h5>
            <a href="{{ route('category.create') }}">
                <button type="button" class="btn btn-success"><i class="fa fa-plus-circle" aria-hidden="true"></i>  Add Category</button>
            </a>
            <div class="my-3"></div>
            <div class="row">
                <div class="col-12">
                    <table class="table table-striped" id="myTable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Category</th>
                                <th>Description</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp @foreach ($data_category as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->category_name }}</td>
                                <td>{{ $item->description }}</td>
                                <td>
                                    <form action="{{ route('category.destroy' , $item->category_id) }}" method="post">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button type="submit" class="btn btn-primary" onclick="return confirm('Are you sure to delete it?')">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div> {{-- end of conten --}}
    </div>
    </div>
</div>
@endsection

resources/views/dashboard/editBook.blade.php
@extends('mainTheme.main') 

@section('title' , 'Edit book')

@section('content')



<div class="container-fluid">
    @foreach ($data_book as $item)
  <div class="row">
      <div class="col-lg-12">
            @if(Session::has('alert-success'))
            <div class="alert alert-success">
                <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
            </div>
            @endif
        <div class="g-card">
        <div class="in-card">
        <form action="{{ route('bookStore.update' , $item->book_id) }}" class="form" method="post">
          {{ csrf_field() }}
          {{ method_field('PUT') }}

          <h5>Manage Book Here</h5>
          <p class="text-right smallin">Silahkan isi sesuai dengan ketentuan</p>
          <div class="my-3"></div>
          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Book Name<br>
                <span class="small40li">Sesuaikan nama center anda dengan benar</span>
              </p>
            </div>
            <div class="col-lg-7">
              <div class="form-group">
                <input id="first" class="form-input" type="text" name="b_name" value="{{ $item->book_name }}"/>
                @if ($errors->has('book_name'))
                      <span class="small40li" style="color:red">
                          <strong>{{ $errors->first('book_name') }}</strong>
                      </span>
                @endif
              </div>
            </div>
          </div>
          
          <hr class="my-5">
          
          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Book Deskription <br>
                <span class="small40li">Sesuaikan nama center anda dengan benar</span>
              </p>
            </div>

            <div class="col-lg-7">
              <div class="form-group">
                  <textarea id="second" class="form-input" name="b_deskrip" rows="6">{{ $item->description }}</textarea>
              </div>
            </div>
          </div>

          <hr class="my-5">

          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Price <br>
                <span class="small40li">Sesuaikan nama center anda dengan benar</span>
              </p>
            </div>

            <div class="col-lg-7">
              <div class="form-group">
                <input id="first" class="form-input" type="number" name="b_price" value="{{ $item->price }}"/>
              </div>
            </div>
          </div>

          <hr class="my-5">

          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Total Stuff <br>
                <span class="small40li">Sesuaikan nama center anda dengan benar</span>
              </p>
            </div>

            <div class="col-lg-7">
              <div class="form-group">
                <input id="first" class="form-input" type="number" name="b_total_stuff" value="{{ $item->total_stuff }}"/>
              </div>
            </div>
          </div>

          <hr class="my-5">

          <!-- midle of end -->
          <div class="row">
            <div class="col-lg-5">
              <p class="small40">Catalog
                <br>
                <span class="small40li">NB: Before using it. Make Category in "Book Category"</span>
              </p>
            </div>

            <div class="col-lg-7">
              <div class="form-group">
                <select class="form-control form-input" name="b_catalog">
                    @foreach ($data_catalog as $item2)
                        <option value="{{ $item2->category_id }}">{{ $item2->category_name }}</option>
                    @endforeach
                </select>
              </div>
            </div>
          </div>

          <div class="my-5"></div>

          <div class="row">
            <div class="col-lg-12">
              <button type="submit" class="btn btn-success">Save The Changes</button>                                
            </div>
          </div>
          
          <div class="my-1"></div>

        </form>
        <div class="row">
            <div class="col-12">
                    <form action="{{ route('bookStore.destroy' , $item->book_id) }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-primary" onclick="return confirm('Are you sure to delete it?')">Delete</button>
                    </form>
            </div>
        </div>

        </div>
      </div>
      </div>

  </div>
  @endforeach
</div>

@endsection

resources/views/dashboard/listBook.blade.php
@extends('mainTheme.main') 

@section('title' , 'List Book')

@section('content') 
@if(Session::has('alert-success'))
<div class="alert alert-success">
    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
</div>
@endif
<div class="container-fluid">
    <div class="row">
        {{-- the batas konten --}}
        <div class="col-lg-12 g-card">
            <div class="in-card">
            <h5>List Books</h5>
            <div class="my-3"></div>
            <div class="row">
                <div class="col-12">
                    <table class="table table-striped" id="myTable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Book Name</th>
                                <th>Description</th>
                                <th>Prices</th>
                                <th>Total_Stuff</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp @foreach ($data_book as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->book_name }}</td>
                                <td>{{ $item->description }}</td>
                                <td>Rp. {{ number_format($item->price) }}</td>
                                <td>{{ $item->total_stuff }} Book</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div> {{-- end of conten --}}
    </div>
    </div>
</div>
@endsection

resources/views/dashboard/main.blade.php
@extends('mainTheme.main') 

@section('title' , 'Dashboard')

@section('content')
<div class="container-fluid">
  <div class="row">
    {{-- the batas konten --}}
    <div class="col-lg-12">
      <div class="g-card">
        <div class="in-card">
          <h1 class="display-4">View Product
          </h1>
          <p class="smallin">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto in eaque aliquam obcaecati ipsum fugit laboriosam
            facere id incidunt eligendi est illo possimus, sunt dolorem quis mollitia officiis magnam quos!</p>
        </div>
        <div class="line-card"></div>
        <div class="card-button">Take the Data</div>
      </div>
    </div>{{-- end of conten --}} {{-- the batas konten --}}
    <div class="col-sm-12 col-md-6 col-lg-6">
      <div class="g-card">
        <div class="in-card">
          <h1 class="display-4">Add New
          </h1>
          <p class="smallin">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto in eaque aliquam obcaecati ipsum fugit laboriosam
            facere id incidunt eligendi est illo possimus, sunt dolorem quis mollitia officiis magnam quos!</p>
        </div>
        <div class="line-card"></div>
        <div class="card-button">Take the Data</div>
      </div>
    </div> {{-- end of conten --}} {{-- the batas konten --}}
    <div class="col-sm-12 col-md-6 col-lg-6">
      <div class="g-card">
        <div class="in-card">
          <h1 class="display-4">Manage Product
          </h1>
          <p class="smallin">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto in eaque aliquam obcaecati ipsum fugit laboriosam
            facere id incidunt eligendi est illo possimus, sunt dolorem quis mollitia officiis magnam quos!</p>
        </div>
        <div class="line-card"></div>
        <div class="card-button">Take the Data</div>
      </div>
    </div> {{-- end of conten --}} {{-- the batas konten --}}
    <div class="col-lg-12">
      <div class="g-card">
        <div class="in-card">
          <h1 class="display-4">Manage Admin
          </h1>
          <p class="smallin">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto in eaque aliquam obcaecati ipsum fugit laboriosam
            facere id incidunt eligendi est illo possimus, sunt dolorem quis mollitia officiis magnam quos!</p>
        </div>
        <div class="line-card"></div>
        <div class="card-button">Take the Data</div>
      </div>
    </div> {{-- end of conten --}}
  </div>
</div>
@endsection

resources/views/dashboard/manageBook.blade.php
@extends('mainTheme.main')

@section('title' , 'Manage Books')

@section('content')
<div class="container-fluid">
        <div class="row">
        {{-- the batas konten --}}
        @foreach ($data_book as $item)
        <div class="col-lg-4">
            <div class="g-card">
                <div class="in-card-m">
                  <h1>{{$item->book_name}}
                  </h1>
                  <p class="small40">Available: {{ $item->total_stuff }} product</p>
                  <p class="smallin">{{$item->description}}</p>
                </div>
                <div class="line-card"></div>
                <a href="{{ route('bookStore.edit' , $item->book_id) }}">
                <div class="card-button">Manage</div>
                </a>
              </div>
        </div> {{-- end of conten --}}    
        @endforeach
        </div>
      </div>
@endsection

resources/views/loginHome.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mainTheme/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>@yield('title')</title>
  <link rel="stylesheet" href="{{ URL::to('css/app.css') }}">
  <link rel="stylesheet" href="{{ URL::to('css/mStyle.css') }}">
</head>

<body>
  <div class="bgDark">
    <div class="nav-fix text-right">
      @php $mytime = Carbon\Carbon::now(); echo $mytime->toDateTimeString(); @endphp
    </div>
    <div class="wrap-nav">
      <div id="nav-show">
        <div class="logohere">
          Book Store
        </div>
        <div class="the-users">
            {{ Auth::user()->name }}
        </div>
        <a href="{{ url('/dashboard') }}">
        <h3><i class="fa fa-dashboard" aria-hidden="true"></i> Dashboard</h3>
        </a>
        <a href="{{ route('bookStore.create') }}">
          <h3><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Book</h3>
        </a>
        <a href="{{ route('category.index') }}">        
          <h3><i class="fa fa-puzzle-piece" aria-hidden="true"></i> Book Category</h3>
        </a>
        
        <a href="{{ route('bookStore.index') }}">  
        <h3><i class="fa fa-file-text-o" aria-hidden="true"></i> List Book</h3>
        </a>

        <a href="{{ url('/ManageBook') }}">  
        <h3><i class="fa fa-wrench" aria-hidden="true"></i> Manage Book</h3>
        </a>
        <hr>
        <a href="{{ route('logout') }}"
                      onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
        <h3><i class="fa fa-sign-out" aria-hidden="true"></i> Sign Out</h3>
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
         </form>
      </div>
      <div id="nav-hide">
      </div>
      <div id="content">
        @yield('content')
      </div>
    </div>
  </div>
  {{-- script jQuery --}}
  <script src="{{ URL::to('js/app.js') }}"></script>
  <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script>
    $(document).ready(function () {
      $('#myTable').DataTable();

      $('input , textarea').focus(function () {
        $(this).parents('.form-group').addClass('focused');
      });

      $('input , textarea').blur(function () {
        var inputValue = $(this).val();
        if (inputValue == "") {
          $(this).removeClass('filled');
          $(this).parents('.form-group').removeClass('focused');
        } else {
          $(this).addClass('filled');
        }
      })

    })
  </script>
</body>

</html>